인기 상품 서비스 학습 테스트
3Juhwan/aengdulab pull request #14
Opened 2024-11-15 01:31 UTC by khabh

#13

2024-11-17 14:50 UTC, 3Juhwan requested changes
감자~ 흠잡을 곳 없이 아주 잘 해주셨네요 🥔👍 (포테이토 따봉)
궁금한 것과 사소한 코멘트 조금 남겨보았어요. 
보고 답변해 주시면 감사하겠습니다 😀

2024-11-17 14:50 UTC, 3Juhwan commented on trend-item/src/test/java/com/aengdulab/trenditem/supports/TimeMeasure.java
> +    private static final Logger log = LoggerFactory.getLogger(TimeMeasure.class);
이 부분 감자가 제 pr에 코멘트 달았듯이, 테스트에서 로깅은 `@Slf4j` 사용으로 통일하죠!

2024-11-17 14:50 UTC, 3Juhwan commented on trend-item/PROBLEM.md
> +        > 인기 점수 = 댓글 수 * 4 + 좋아요 수 * 5 + 조회 수 * 3 + 글자 수 * 0.5 + (-1) * 게시 후 경과 시간(m)
구체적인 가중치를 넣은 이유, 그리고 이 가중치를 선택한 이유가 무엇인가요?

2024-11-17 14:50 UTC, 3Juhwan commented on trend-item/src/main/java/com/aengdulab/trenditem/config/ClockConfig.java
> +    @Bean
```suggestion
public class ClockConfig {

    @Bean
```
너무 사소한 코멘트

2024-11-17 14:50 UTC, 3Juhwan commented on trend-item/src/main/java/com/aengdulab/trenditem/config/ClockConfig.java
> +public class ClockConfig {
테스트를 위한 시계 맞나요? 레벨2 때 했던 건데, 반갑네요 ✋

2024-11-17 14:50 UTC, 3Juhwan commented on trend-item/src/main/java/com/aengdulab/trenditem/domain/Item.java
> +        validateViews(views);
위 생성자들이 사용되는 위치를 보니까 다음과 같아요! 

- 1번째 친구: 테스트에서만 사용
- 2번째 친구: 미사용
- 3번째 친구: 테스트에서만 사용
- 4번째 친구: 프로덕션 코드에서 사용하고 있어요

이 클래스에 유독 생성자가 많아서, 어떤 상황에 어떤 생성자를 써야 할지 파악하기 어려웠어요. 
지금 상황을 보니, 추가 생성자를 여는 게 어쩔 수 없다고 생각되네요 🥹

2024-11-17 14:50 UTC, 3Juhwan commented on trend-item/src/main/java/com/aengdulab/trenditem/domain/Item.java
> +    }
이 친구가 `getContentLength()` 위로 올라가면 어떨까요? 게터보다는 위에 있는 게 적절하다 생각해서요!

2024-11-17 14:50 UTC, 3Juhwan commented on trend-item/src/main/java/com/aengdulab/trenditem/domain/Like.java
> +
Like를 하나의 엔티티로 두시다니.. 역정규화하면 쾌감 있겠어요 😂

2024-11-17 14:50 UTC, 3Juhwan commented on trend-item/src/test/java/com/aengdulab/trenditem/domain/TrendItemTest.java
> +    public void testCalculatePopularity() {
메서드 명 수정해 주세요!

2024-11-17 14:50 UTC, 3Juhwan commented on trend-item/src/test/java/com/aengdulab/trenditem/supports/ItemReactions.java
> +
이 네이밍이 무엇인지 궁금해요!

2024-11-18 03:41 UTC, khabh reviewed
꼼꼼한 리뷰 🥔합니다
피드백 반영해서 수정했으니 확인해 주시와요

2024-11-18 03:41 UTC, khabh commented on trend-item/src/main/java/com/aengdulab/trenditem/config/ClockConfig.java
> +public class ClockConfig {
저는 레벨2 미션 할 때도 이거 안 썼습니다 ㅋㅋ 시계가 있는 편이 테스트가 수월할 것 같아서 넣어봤어요

2024-11-18 03:41 UTC, khabh commented on trend-item/src/main/java/com/aengdulab/trenditem/domain/Like.java
> +
감자의 큰그림입니다 🥸

2024-11-18 03:41 UTC, khabh commented on trend-item/PROBLEM.md
> +        > 인기 점수 = 댓글 수 * 4 + 좋아요 수 * 5 + 조회 수 * 3 + 글자 수 * 0.5 + (-1) * 게시 후 경과 시간(m)
숫자를 제시하지 않고 상수라고만 명시하는 경우, 이 문제를 해결할 때 각 상수에 어떤 값을 대입할지 고민하게 될 텐데 그게 학습 측면에서 크게 유의미한 고민이 아니라고 생각해서 제가 임의로 지정했습니다. 최신 상품이 더 잘 노출될 수 있도록 경과 시간이 클수록 점수가 낮아지도록 했고, 나머지 값들은 제가 생각하는 우선순위에 맞춰 가중치를 뒀어요 :)

2024-11-18 03:41 UTC, khabh commented on trend-item/src/main/java/com/aengdulab/trenditem/config/ClockConfig.java
> +    @Bean
중요하죠 🫨

2024-11-18 03:41 UTC, khabh commented on trend-item/src/main/java/com/aengdulab/trenditem/domain/Item.java
> +        validateViews(views);
생성자가 너무 많긴 하네요 😅 일단 ItemService에서 Clock을 사용하고 있으니, LocalDateTime.now()를 직접 호출하는 메서드는 삭제했습니다!

2024-11-18 03:41 UTC, khabh commented on trend-item/src/test/java/com/aengdulab/trenditem/supports/ItemReactions.java
> +
상품과 상품과 관련된 상호작용(댓글, 좋아요)을 가지고 있다는 의미입니다. 사실 이름만 보면 Item 하나와 List<Comment>, List<Like>를 가질 것 같긴 한데, 프로덕션 코드가 아니라서 테스트 편의성을 최우선으로 두고 필드를 다 리스트로 지정했어요.

2024-11-18 06:13 UTC, 3Juhwan commented on trend-item/src/test/java/com/aengdulab/trenditem/supports/ItemReactions.java
> +
그런 의미였군요! 좋은데요? 전 마음에 듭니다 👍

2024-11-18 06:14 UTC, 3Juhwan commented on trend-item/PROBLEM.md
> +        > 인기 점수 = 댓글 수 * 4 + 좋아요 수 * 5 + 조회 수 * 3 + 글자 수 * 0.5 + (-1) * 게시 후 경과 시간(m)
학습의 목적에 중요한 부분이 아니라 생각하여, 감자의 의견을 지지합니다 🥔

2024-11-19 01:29 UTC, 3Juhwan approved these changes
고생하셨습니다 😀

2024-11-19 01:29 UTC, merged