분산 환경 메일 발송 서비스 학습 테스트
3Juhwan/aengdulab pull request #15
Opened 2024-11-15 18:30 UTC by 3Juhwan

2024-11-16 14:07 UTC, khabh requested changes
안녕하세요 망쵸
주제가 까다로웠는데도 코드 깔끔하게 잘 구현해 주셨네요 👍
코멘트 확인해 주세요~

2024-11-17 15:31 UTC, 3Juhwan commented on distributed-mail/src/test/java/com/aengdulab/distributedmail/MultiServerRequestTest.java
> +    void 다중화된_서버에서_균등하고_중복_없이_모든_구독자에게_메일을_발송한다() throws Exception {
이 문제 저도 인지하고 있었어요 😢 

로컬 환경에 따라, 위 예외가 발생하는데요. 
compose로 db와 server 컨테이너를 띄우는 과정에서, db 컨테이너 내부의 mysql 서버가 준비되기 전에 server 컨테이너에서 springboot가 실행되어서 발생한 문제에요. 
compose에서 db와 server 컨테이너 간의 의존성을 걸어두었지만, 이는 단순히 컨테이너의 실행 의존성이지 컨테이너 내부의 환경에 대한 의존성이 아니더군요. 

db 컨테이너를 띄우고 mysql server에 ping을 날리는 시도를 해보았지만 안되더군요. 다른 방법을 고민해서 적용할게요!

2024-11-18 06:43 UTC, 3Juhwan commented on distributed-mail/src/test/java/com/aengdulab/distributedmail/MultiServerRequestTest.java
> +    void 다중화된_서버에서_균등하고_중복_없이_모든_구독자에게_메일을_발송한다() throws Exception {
저의 환경에서는 테이블이 생성되지 않는 문제는 발생하지는 않네요 :(
감자에게 별도의 문의한 결과, schema.sql을 수정하니까 된다고 해서 저도 그렇게 해결했어요!

2024-11-18 07:04 UTC, 3Juhwan commented on distributed-mail/src/main/java/com/aengdulab/distributedmail/service/MailSenderImpl.java
> +            Thread.sleep(100);
감자의 질문을 제가 이해한 바는, 메일을 전송해야 하는 객체인데 단순히 스레드를 멈추기만 한 이유가 무엇인지에요. 질문 의도와 맞을까요? 이에 대해 고민한 점을 공유할게요! 피드백 주세요 😀 

외부 메일 서비스를 사용하여 실제로 메일 전송은 어렵다고 생각했어요. 아무래도 테스트할 때, 실제 매일을 전송하면 곤란하겠죠? 
다음으로, 테스트를 위해 도커로 smtp 서버를 구성하는 방법을 고민해 보았어요. 음,,, 구성하는 비용이 작지 않은데, 학습이라는 목적에 있어 그만큼 얻는 게 있는지 모르겠더라구요. 

명확히 하기 위해 학습 목적을 돌아보았어요. `분산된 환경에서 균등하고 중복 없이 사용자에게 메일을 발송한다.`를 고려했을 때, 메일을 직접 발송하는 것이 학습에 도움되진 않을 것 같아요. 

다만, 고려하면 좋을 부분이 있었는데요. 실제 메일 서버를 연결할 경우에 google smtp의 경우에 초당 약 14개의 메일만 보낼 수 있어요. 이를 고려하여 MailSender가 초당 10개의 메일을 보낸다고 가정하여 100ms의 딜레이를 걸었어요!

2024-11-18 15:18 UTC, 3Juhwan commented on distributed-mail/src/main/java/com/aengdulab/distributedmail/domain/SubscribeQuestionMessage.java
> +public class SubscribeQuestionMessage {
저도 이 친구를 dto라고 생각하고 구현했어요 :) 
혹시 domain 패키지에 있는 게 어색할까요? 어디에 위치하는 게 적절할지 몰라서, 이렇게 두었어요. 
아이디어 부탁합니다!

2024-11-18 15:26 UTC, 3Juhwan commented on distributed-mail/src/test/java/com/aengdulab/distributedmail/MultiServerRequestTest.java
> +        assertThat(sentMailCount).isEqualTo(SUBSCRIBER_COUNT);
[중복 없이 모든 사용자가 질문을 받았는지 검증](https://github.com/3Juhwan/aengdulab/pull/15/commits/7f647feecdf5380f60bfc1cc21dafe94414a055a)에서 수정했어요! 
메일 발송 이벤트를 조회하고 distinct한 Subscribe 수를 셌는데, 어떤가요?

2024-11-18 15:54 UTC, 3Juhwan commented
감자~ 피드백 반영했습니다. 
감자에게 다시 피드백 받고, 추가로 수정할 부분이 있을 것 같아요. 

현재 한 가지 문제가 더 있는데요. 서버를 두 개의 컨테이너에서 띄우고 있어요. dockerfile를 확인하면 로컬에 빌드한 jar를 그대로 사용하게 했어요. 
이로 인한 문제는 local 파일을 수정할 경우에 빌드를 새로하고, 컨테이너를 새로 띄워야 변경 내용이 컨테이너에 반영된다는 점이에요. 이를 해결해야 학습할 때 불편함이 없을 것 같은데요. 문제는 local 파일 수정할 때마다 새로 빌드하는 것이 시간이 꽤 걸린다는 거에요. 
이걸 해결하려 gradle에 대해 좀 학습했는데, 문제를 해결하기에 아직 부족한 것 같아요. 하루 더 고민해 보고 최종 반영해야 할 것 같아요.

2024-11-18 23:48 UTC, khabh approved these changes
안녕하세요 망쵸 :)
제가 수정 요청 드린 부분은 다 잘 반영해 주셔서, 망쵸가 말한 문제가 어느 정도 해결되면 바로 머지해도 될 것 같습니다 고생 많으셨어요 🥔

2024-11-18 23:48 UTC, khabh commented on distributed-mail/src/main/java/com/aengdulab/distributedmail/domain/SubscribeQuestionMessage.java
> +public class SubscribeQuestionMessage {
망쵸가 SubscribeQuestionMessage에 대해 어떻게 생각하는지 궁금했던 게 가장 큽니다 :)
dto 패키지를 따로 만들어도 좋고, 현상 유지하면서 domain으로 사용될 수 있도록 두는 것도 괜찮은 것 같아요.

2024-11-18 23:48 UTC, khabh commented on distributed-mail/src/main/java/com/aengdulab/distributedmail/service/MailSenderImpl.java
> +            Thread.sleep(100);
> 감자의 질문을 제가 이해한 바는, 메일을 전송해야 하는 객체인데 단순히 스레드를 멈추기만 한 이유가 무엇인지에요. 질문 의도와 맞을까요? 

네, 맞아요. 콘텐츠를 만들 때 실제 메일 전송이 어려울 거라는 건 어느 정도 예상하고 있었는데, 망쵸가 어떤 과정으로 이런 결정을 내리게 된 건지 궁금했어요. 또 MailSender 부분만 인터페이스로 분리되어 있어서, 이 학습 자료를 사용하게 될 사람이 직접 구현하라는 의도였는지 그저 추상화한 건지도 알고 싶었구요. 

> 구성하는 비용이 작지 않은데, 학습이라는 목적에 있어 그만큼 얻는 게 있는지 모르겠더라구요. 분산된 환경에서 균등하고 중복 없이 사용자에게 메일을 발송한다.를 고려했을 때, 메일을 직접 발송하는 것이 학습에 도움되진 않을 것 같아요.

망쵸 말을 듣고 보니 직접 메일을 발송하는 방식으로 얻는 이점에 비해 그걸 구현하는 데 드는 비용이 너무 큰 것 같긴 하네요. 현황을 유지해도 좋을 것 같아요 ㅎㅎ

실제 구글의 사례를 가지고 딜레이 시간을 유추한 거 너무 좋습니다 👍

2024-11-18 23:48 UTC, khabh commented on distributed-mail/src/test/java/com/aengdulab/distributedmail/MultiServerRequestTest.java
> +    void 다중화된_서버에서_균등하고_중복_없이_모든_구독자에게_메일을_발송한다() throws Exception {
도커는 너무 어렵네요 🥲 schema.sql을 수정했을 때 제 환경에서는 잘 동작하니, 나중에 다른 문제를 발견한다면 그때 해결해도 좋을 것 같아요

2024-11-18 23:48 UTC, khabh commented on distributed-mail/src/test/java/com/aengdulab/distributedmail/MultiServerRequestTest.java
> +        assertThat(sentMailCount).isEqualTo(SUBSCRIBER_COUNT);
저는 모든 SentMailEvent을 하나씩 확인하는 걸 떠올렸는데 이 방법이 훨씬 간결하네요, 좋습니다 👍

2024-11-18 23:48 UTC, khabh commented on distributed-mail/PROBLEM.md
> +    - 일부 서버가 다운되어도 **모든 사용자에게 메일을 발송**해야 한다.
`- 일부 서버가 다운되어도 **모든 사용자에게 메일을 발송**해야 한다.`

16번째 줄에만 달아 놓은 건데 깃허브에서 여러 줄로 표시된 것 같네요. 서버 중 하나가 다운된 상태에서도 모든 사용자에게 메일이 잘 발송되는지 테스트하는 것에 대해 말한 거였습니다. 테스트를 구성하는 비용이 너무 크거나 해당 테스트 자체가 불필요한 상황이라면 추가하지 않아도 괜찮습니다. 망쵸가 선택적으로 반영해 주세요 :)

2024-11-18 23:48 UTC, khabh commented on distributed-mail/src/main/java/com/aengdulab/distributedmail/domain/Subscribe.java
> +    }
오류 발생 확률이 더 낮아져서 현재 코드가 훨씬 좋은 것 같아요 👍
사실 저도 코멘트 남기면서 구현 로직이 조금 복잡할 수 있겠다고 생각했는데 잘 반영해 주셨네요 고생하셨습니다

2024-11-19 14:07 UTC, 3Juhwan commented
감자~ 코드 리뷰 부탁드려요. 좀 많이 수정해서 리뷰가 어려울 수 있는데, 미안합니다. 
변경한 의도를 먼저 알고 코드를 보면 이해가 수월할 것 같아요! 

### **도커 컴포즈로 애플리케이션 서버를 다중화하고 테스트 실행하기** vs **테스트 실행 시 테스트 컨테이너 실행하기** 

- 테스트 실행 시간
  - 도커 컴포즈 방식은 처음 컨테이너를 구성하고 끝이기 때문에, 테스트를 여러 번 실행해도 순수 테스트 실행 시간만 걸린다. 
  - 테스트 컨테이너 방식은 테스트마다 컨테이너를 띄우기 때문에 오래 걸린다. 
  - 결론: 둘다 오래 걸린다. 
- 빌드 자동화
  - 도커 컴포즈 방식은 코드가 수정될 때마다 매번 새로운 이미지를 빌드하고 컨테이너를 띄워야 한다. 
  - 테스트 컨테이너 방식도 도커 이미지를 기반으로 실행되기에 새로 이미지 빌드하고 컨테이너를 띄운다. 이것도 자동화는 가능하지만 새로운 라이브러리를 추가해야 한다. 
  - 결론: 둘다 테스트하기 위해 비용이 크다. 
- 로그
  - 도커 컴포즈 방식은 docker logs로 서버 로그를 확인할 수 있다. 
  - 테스트 컨테이너 방식은 확인하기 어렵다. 
  - 결론: 둘다 로그를 확인하기 어렵다. 

### Spring Boot 컨테이너 제거

위에 비교했듯이 도커를 사용하는 이점을 전혀 찾을 수 없었어요. 그래서 Spring Boot 컨테이너를 컴포즈에서 제거했어요. 
대신 IntelliJ에서 직접 실행하는 방법을 택했어요. 위에 언급한 모든 단점을 커버하는 방식이에요. 
또한, `일부 서버가 다운되는 상황에 메일이 정상적으로 발송되는지`와 같은 검증도 학습하는 사람이 제어하기 쉬워요. 일부 서버를 꺼버리면 되니깐요! 
IntelliJ에서 다중 서버를 구성하는 것이 어려울 수 있는데, 이는 PROBLEM.md에 정리해 두었어요! 

### SMTP 도커 컨테이너 추가

SMTP 서버를 추가했어요. 학습 측면에서 큰 이점은 없다고 생각하지만, 실제와 비슷한 코드면 학습에 좀더 몰입할 수 있을 거라 생각해서요! 
SMTP 서버는 가벼운 MailHog를 사용했어요. 

### data.sql 제거

역시 sql로 작성하는 건 별로더군요. Subscribe 수를 늘리고 싶어도 관리 포인트가 테스트 코드와 sql로 분산되어 있는 게, 불편했어요. 
코드로 데이터를 삽입하고 삭제하도록 수정했어요!

2024-11-19 14:11 UTC, 3Juhwan commented on distributed-mail/PROBLEM.md
> +    - 일부 서버가 다운되어도 **모든 사용자에게 메일을 발송**해야 한다.
이제 이 부분은 사용자가 직접 IntelliJ로 일부 서버를 다운하고 테스트할 수 있어요!

2024-11-19 14:12 UTC, 3Juhwan commented on distributed-mail/src/test/java/com/aengdulab/distributedmail/MultiServerRequestTest.java
> +        assertThat(sentMailCount).isEqualTo(SUBSCRIBER_COUNT);
추가로 smtp 서버에 질의하여 발송한 메일을 검증하도록 수정했어요!

2024-11-20 12:08 UTC, 3Juhwan commented on distributed-mail/PROBLEM.md
> +- 설정한 모든 Spring Boot 서버를 한 번에 실행 및 종료할 수 있습니다.
```suggestion
- 설정한 모든 Spring Boot 서버를 한 번에 실행 및 종료할 수 있습니다. 

```

2024-11-20 13:17 UTC, 3Juhwan commented
감자, 리뷰 감사합니다 😀 
이만 머지할게요!

2024-11-20 13:17 UTC, merged