티켓 재고 관리 도메인 설계
3Juhwan/aengdulab pull request #3
Opened 2024-10-29 13:43 UTC by khabh

2024-10-31 06:14 UTC, 3Juhwan requested changes
감자 도메인 코드 작성하느라 고생했어요 😀 
동시성 테스트도 적절하게 잘 작성해 주었네요. 
코멘트 확인 및 반영 후 머지하면 될 것 같습니다.

2024-10-31 06:14 UTC, 3Juhwan commented on ticket/src/test/java/com/aengdulab/ticket/service/MemberTicketServiceConcurrencyTest.java
> +        try (ExecutorService executorService = Executors.newFixedThreadPool(threadCount)) {
A: try-catch wit resources를 사용해서 indent가 추가되네요! 이게 가독성을 저하한다고 생각해서 ExecutorService를 직접 shutdown하는 방법을 찾아 보았는데, auto-close를 사용하는 게 더 안전해 보이네요 :)

2024-10-31 06:15 UTC, 3Juhwan commented
아 그리고, 테스트에 한글 메서드명이 불편하면 클래스 수준에 `@SuppressWarnings("NonAsciiCharacters")` 같은 어노테이션을 붙여도 좋을 것 같아요.

2024-10-31 06:37 UTC, 3Juhwan commented on ticket/src/main/java/com/aengdulab/ticket/domain/Member.java
> +@EqualsAndHashCode(of = "id")
`@EqualsAndHashCode(onlyExplicitlyIncluded = true)`를 적용하는 건 어떤가요? 그럼 코드가 아래와 같이 변경될 거에요. 

```java
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class Member {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @EqualsAndHashCode.Include
    private Long id;

}
```

2024-10-31 14:57 UTC, 3Juhwan approved these changes

2024-10-31 15:01 UTC, merged

2024-10-31 23:15 UTC, khabh reviewed
바보 감자 눈동자에 건배 🫠🫠

2024-11-01 01:18 UTC, 3Juhwan commented
고민한 내용 공유해 주셔서 감사해요 😀 고려하지 않던 내용인데 덕분에 새로 알게 되었어요 👍 이런 활동이 계속되면 좋겠어요. 저도 노력해 볼게요! 

`onlyExplicitlyIncluded = true` 옵션에 대해, 어제 코멘트를 달고 고민해 보았고 컨벤션 영역이라 생각했어요. 해당 옵션을 사용하면 확장성 측면에서 좋겠지만, 감자가 언급한 단점도 있어요. 또, 생각해보면 엔티티의 경우에 주로 id만을 동등성 비교에 사용할테니 해당 옵션을 사용해도, 하지 않아도, 결과는 비슷하다고 생각해요. 

엔티티 객체이기에 **id 필드만을 동등성 비교에 사용한다**와 **id 필드명은 변경하지 않는다**는 사실이 쉽게 변하진 않을 것 같아요. 그렇다면 `onlyExplicitlyIncluded` 옵션을 사용하더라도 id 필드만을 동등성 비교에 사용한다는 것을 아니까 어떤 필드가 동등성 비교에 사용되는지 확인하지 않아도 돼요. 언급해 주신 단점이 모호해지는 지점이라 생각해요. 

그런데 만약에 동등성 비교 정책이 변경될 경우를 생각해 보면, onlyExplicitlyIncluded 옵션을 사용했다면 모든 필드를 확인해야 될거에요. 이때 휴먼 에러가 발생할 가능성이 있다고 생각해요. 

결국 컨벤션 영역이라 생각 들고, 이런 경우에 공수가 가장 적게 드는 방향을 좋아하는데요. 현재 작성한 대로 유지하는 것이 좋아 보여요 :)